fix: sql command should use right scope
constructor was not using the right scope, so the test failed with the
following error:
TypeError: Cannot read property 'getTypeParser' of undefined